import { sql } from "drizzle-orm";
import { boolean, index, integer, pgTable, real, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

const sqliteTable = pgTable;

const timestamps = { createdAt: timestamp("created_at", { mode: "string", withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true }).notNull().defaultNow() };
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull(), displayName: text("display_name").notNull(), ...timestamps }, t => [uniqueIndex("users_email_uq").on(t.email)]);
export const anonymousCreationLimits = sqliteTable("anonymous_creation_limits", { bucketKey: text("bucket_key").primaryKey(), count: integer("count").notNull().default(0), expiresAt: timestamp("expires_at", { mode: "string", withTimezone: true }).notNull() });
export const trips = sqliteTable("trips", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: text("title").notNull(), destination: text("destination").notNull(), startDate: text("start_date").notNull(), endDate: text("end_date").notNull(), status: text("status", { enum: ["draft", "generating", "ready", "archived"] }).notNull().default("draft"), revision: integer("revision").notNull().default(1), currency: text("currency").notNull().default("CNY"), budgetTotal: real("budget_total"), constraintsJson: text("constraints_json").notNull().default("{}"), sourceType: text("source_type").notNull().default("user_added"), ...timestamps }, t => [index("trips_user_idx").on(t.userId), index("trips_status_idx").on(t.status)]);
export const tripDays = sqliteTable("trip_days", { id: text("id").primaryKey(), tripId: text("trip_id").notNull().references(() => trips.id, { onDelete: "cascade" }), dayIndex: integer("day_index").notNull(), date: text("date").notNull(), title: text("title").notNull(), weatherJson: text("weather_json"), summaryJson: text("summary_json").notNull().default("{}"), ...timestamps }, t => [uniqueIndex("trip_days_trip_index_uq").on(t.tripId, t.dayIndex)]);
export const places = sqliteTable("places", { id: text("id").primaryKey(), provider: text("provider").notNull(), providerPlaceId: text("provider_place_id"), name: text("name").notNull(), address: text("address"), latitude: real("latitude"), longitude: real("longitude"), category: text("category"), sourceType: text("source_type").notNull(), verifiedAt: text("verified_at"), rawJson: text("raw_json").notNull().default("{}"), ...timestamps }, t => [index("places_provider_idx").on(t.provider, t.providerPlaceId)]);
export const itineraryItems = sqliteTable("itinerary_items", { id: text("id").primaryKey(), tripId: text("trip_id").notNull().references(() => trips.id, { onDelete: "cascade" }), dayId: text("day_id").notNull().references(() => tripDays.id, { onDelete: "cascade" }), placeId: text("place_id").references(() => places.id, { onDelete: "set null" }), type: text("type").notNull(), title: text("title").notNull(), startTime: text("start_time").notNull(), durationMinutes: integer("duration_minutes").notNull(), position: integer("position").notNull(), notes: text("notes").notNull().default(""), locked: boolean("locked").notNull().default(false), lockTime: boolean("lock_time").notNull().default(false), sourceType: text("source_type").notNull(), cost: real("cost"), metadataJson: text("metadata_json").notNull().default("{}"), ...timestamps }, t => [index("items_trip_day_idx").on(t.tripId, t.dayId, t.position)]);
export const routeSegments = sqliteTable("route_segments", { id: text("id").primaryKey(), tripId: text("trip_id").notNull().references(() => trips.id, { onDelete: "cascade" }), dayId: text("day_id").notNull().references(() => tripDays.id, { onDelete: "cascade" }), fromItemId: text("from_item_id").notNull(), toItemId: text("to_item_id").notNull(), mode: text("mode").notNull(), distanceMeters: integer("distance_meters"), durationMinutes: integer("duration_minutes"), cost: real("cost"), geometryJson: text("geometry_json"), detailsJson: text("details_json").notNull().default("{}"), sourceType: text("source_type").notNull(), verifiedAt: text("verified_at"), ...timestamps }, t => [index("routes_day_idx").on(t.dayId)]);
export const tripVersions = sqliteTable("trip_versions", { id: text("id").primaryKey(), tripId: text("trip_id").notNull().references(() => trips.id, { onDelete: "cascade" }), revision: integer("revision").notNull(), label: text("label").notNull(), snapshotJson: text("snapshot_json").notNull(), createdBy: text("created_by").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t => [uniqueIndex("versions_trip_revision_uq").on(t.tripId, t.revision)]);
export const tripOperations = sqliteTable("trip_operations", { id: text("id").primaryKey(), tripId: text("trip_id").notNull().references(() => trips.id, { onDelete: "cascade" }), baseRevision: integer("base_revision").notNull(), resultRevision: integer("result_revision"), status: text("status").notNull(), summary: text("summary").notNull(), operationsJson: text("operations_json").notNull(), idempotencyKey: text("idempotency_key").notNull(), createdBy: text("created_by").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t => [uniqueIndex("operations_idempotency_uq").on(t.tripId, t.idempotencyKey)]);
export const mcpServers = sqliteTable("mcp_servers", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), providerKey: text("provider_key").notNull(), name: text("name").notNull(), endpoint: text("endpoint").notNull(), authMode: text("auth_mode").notNull(), encryptedSecret: text("encrypted_secret"), enabled: boolean("enabled").notNull().default(true), permission: text("permission").notNull().default("ask"), source: text("source").notNull().default("custom"), lastStatus: text("last_status"), lastError: text("last_error"), ...timestamps }, t => [uniqueIndex("mcp_user_provider_uq").on(t.userId, t.providerKey)]);
export const mcpCallLogs = sqliteTable("mcp_call_logs", { id: text("id").primaryKey(), userId: text("user_id").notNull(), serverId: text("server_id").notNull(), toolName: text("tool_name").notNull(), status: text("status").notNull(), durationMs: integer("duration_ms").notNull(), errorCode: text("error_code"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t => [index("mcp_logs_user_idx").on(t.userId, t.createdAt)]);
export const aiSettings = sqliteTable("ai_settings", { userId: text("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), provider: text("provider").notNull().default("openai-compatible"), baseUrl: text("base_url").notNull().default("https://api.openai.com/v1"), model: text("model").notNull().default("gpt-5-mini"), thinkingEnabled: boolean("thinking_enabled").notNull().default(false), encryptedApiKey: text("encrypted_api_key"), ...timestamps });
export const aiJobs = sqliteTable("ai_jobs", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tripId: text("trip_id").notNull().references(() => trips.id, { onDelete: "cascade" }), prompt: text("prompt").notNull(), useMcp: boolean("use_mcp").notNull().default(true), status: text("status", { enum: ["queued", "running", "completed", "failed", "cancelled"] }).notNull().default("queued"), stage: text("stage").notNull().default("discovering_mcp"), progress: integer("progress").notNull().default(0), attempts: integer("attempts").notNull().default(0), contextJson: text("context_json").notNull().default("{}"), resultJson: text("result_json"), error: text("error"), startedAt: text("started_at"), completedAt: text("completed_at"), ...timestamps }, t => [index("ai_jobs_user_trip_idx").on(t.userId, t.tripId, t.createdAt), index("ai_jobs_status_idx").on(t.status, t.updatedAt)]);
export const shareLinks = sqliteTable("share_links", { id: text("id").primaryKey(), tripId: text("trip_id").notNull().references(() => trips.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull(), expiresAt: text("expires_at"), revokedAt: text("revoked_at"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t => [uniqueIndex("share_token_uq").on(t.tokenHash)]);
