#!/usr/bin/env bash
# Configure Feishu webhook for flight monitor notifications.
# Usage:
#   bash scripts/setup-feishu.sh <webhook_url>
#   bash scripts/setup-feishu.sh   # interactive
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
EXAMPLE="$ROOT_DIR/.env.example"

webhook="${1:-}"
report_type="${2:-ranked}"
webhook_secret="${3:-${FEISHU_WEBHOOK_SECRET:-}}"

if [[ -z "$webhook" ]]; then
  echo "飞书自定义机器人 Webhook 配置"
  echo "────────────────────────────"
  echo "1. 打开飞书群 → 设置 → 群机器人 → 添加机器人 → 自定义机器人"
  echo "2. 复制 Webhook 地址（形如 https://open.feishu.cn/open-apis/bot/v2/hook/...）"
  echo ""
  read -r -p "请输入 FEISHU_WEBHOOK_URL: " webhook
fi

if [[ -z "$webhook" ]]; then
  echo "错误：Webhook URL 不能为空" >&2
  exit 1
fi

if [[ ! "$webhook" =~ ^https://open\.feishu\.cn/open-apis/bot/v2/hook/ ]]; then
  echo "警告：URL 格式不像飞书自定义机器人 Webhook，仍将写入 .env" >&2
fi

read -r -p "推送报告类型 [ranked/latest/both] (默认 ranked): " input_report
report_type="${input_report:-$report_type}"

mkdir -p "$(dirname "$ENV_FILE")"
if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "已备份原配置 → ${ENV_FILE}.bak"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-feishu.sh — $(date -Iseconds)
FEISHU_WEBHOOK_URL=$webhook
FEISHU_REPORT=$report_type
FEISHU_WEBHOOK_SECRET=$webhook_secret
# FEISHU_MAX_BYTES=20000
EOF

chmod 600 "$ENV_FILE" 2>/dev/null || true

echo ""
echo "✅ 飞书通报已写入 $ENV_FILE"
echo "   FEISHU_WEBHOOK_URL=${webhook:0:60}..."
echo "   FEISHU_REPORT=$report_type"
echo ""
echo "测试推送：npm run notify:feishu"
echo "监控+推送：npm run monitor:ranked"
