#!/usr/bin/env bash
# Configure Feishu notifications for flight monitor (Open API app bot or webhook).
# Usage:
#   bash scripts/setup-feishu.sh --app <app_id> <app_secret> <chat_id> [ranked|latest|both]
#   bash scripts/setup-feishu.sh <webhook_url> [ranked|latest|both] [webhook_secret] [chat_id]
#   bash scripts/setup-feishu.sh   # interactive
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

mode="webhook"
webhook=""
app_id=""
app_secret=""
chat_id="${FEISHU_CHAT_ID:-}"
report_type="ranked"
webhook_secret="${FEISHU_WEBHOOK_SECRET:-}"

if [[ "${1:-}" == "--app" ]]; then
  mode="app"
  shift
  app_id="${1:-}"
  app_secret="${2:-}"
  chat_id="${3:-}"
  report_type="${4:-ranked}"
elif [[ -n "${1:-}" && "${1:-}" != "--app" ]]; then
  webhook="$1"
  report_type="${2:-ranked}"
  webhook_secret="${3:-${FEISHU_WEBHOOK_SECRET:-}}"
  chat_id="${4:-${FEISHU_CHAT_ID:-}}"
fi

if [[ "$mode" == "app" ]]; then
  if [[ -z "$app_id" || -z "$app_secret" || -z "$chat_id" ]]; then
    echo "飞书应用机器人（Open API）配置"
    echo "────────────────────────────"
    echo "1. 飞书开放平台创建企业自建应用，获取 App ID / App Secret"
    echo "2. 开通权限：im:message:send_as_bot（或 im:message）"
    echo "3. 将应用机器人添加到目标群"
    echo "4. 群 chat_id 形如 oc_xxxxxxxx（可在群设置或 API 中获取）"
    echo ""
    read -r -p "FEISHU_APP_ID: " app_id
    read -r -p "FEISHU_APP_SECRET: " app_secret
    read -r -p "FEISHU_CHAT_ID: " chat_id
  fi
  if [[ -z "$app_id" || -z "$app_secret" || -z "$chat_id" ]]; then
    echo "错误：App ID、App Secret、chat_id 均不能为空" >&2
    exit 1
  fi
else
  if [[ -z "$webhook" ]]; then
    echo "飞书自定义机器人 Webhook 配置"
    echo "────────────────────────────"
    echo "1. 打开飞书群 → 设置 → 群机器人 → 添加机器人 → 自定义机器人"
    echo "2. 复制 Webhook 地址（形如 https://open.feishu.cn/open-apis/bot/v2/hook/...）"
    echo ""
    read -r -p "请输入 FEISHU_WEBHOOK_URL: " webhook
  fi
  if [[ -z "$webhook" ]]; then
    echo "错误：Webhook URL 不能为空" >&2
    exit 1
  fi
  if [[ ! "$webhook" =~ ^https://open\.feishu\.cn/open-apis/bot/v2/hook/ ]]; then
    echo "警告：URL 格式不像飞书自定义机器人 Webhook，仍将写入 .env" >&2
  fi
  if [[ -n "${1:-}" ]]; then
    :
  elif [[ -t 0 ]]; then
    read -r -p "签名校验密钥 FEISHU_WEBHOOK_SECRET（无则回车跳过）: " webhook_secret || true
    read -r -p "推送报告类型 [ranked/latest/both] (默认 ranked): " input_report
    report_type="${input_report:-$report_type}"
  fi
fi

mkdir -p "$(dirname "$ENV_FILE")"
if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "已备份原配置 → ${ENV_FILE}.bak"
fi

if [[ "$mode" == "app" ]]; then
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-feishu.sh --app — $(date -Iseconds)
FEISHU_APP_ID=$app_id
FEISHU_APP_SECRET=$app_secret
FEISHU_CHAT_ID=$chat_id
FEISHU_REPORT=$report_type
# FEISHU_MAX_BYTES=20000
EOF
else
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-feishu.sh — $(date -Iseconds)
FEISHU_WEBHOOK_URL=$webhook
FEISHU_REPORT=$report_type
FEISHU_WEBHOOK_SECRET=$webhook_secret
FEISHU_CHAT_ID=$chat_id
# FEISHU_MAX_BYTES=20000
EOF
fi

chmod 600 "$ENV_FILE" 2>/dev/null || true

echo ""
echo "✅ 飞书通报已写入 $ENV_FILE"
if [[ "$mode" == "app" ]]; then
  echo "   FEISHU_APP_ID=$app_id"
  echo "   FEISHU_APP_SECRET=***"
  echo "   FEISHU_CHAT_ID=$chat_id"
else
  echo "   FEISHU_WEBHOOK_URL=${webhook:0:60}..."
  if [[ -n "$webhook_secret" ]]; then
    echo "   FEISHU_WEBHOOK_SECRET=***（已配置签名校验）"
  fi
  if [[ -n "$chat_id" ]]; then
    echo "   FEISHU_CHAT_ID=$chat_id"
  fi
fi
echo "   FEISHU_REPORT=$report_type"
echo ""
echo "测试推送：npm run notify:feishu:test"
echo "监控+推送：npm run monitor:ranked"
